---
dist: trusty
language: node_js
node_js:
  - 9
cache:
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: nickmask/percy-ui
  bucket: percy-ui
  region: us-east-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: percy-ui
  key: latest.zip
  bundle_type: zip
  application: PercyUi
  deployment_group: PercyUiCodeDeploy
  region: us-east-2
  on: *2
script:
  - zip -r latest * >/dev/null
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip